### ISSUE TITLE
Missing doc version?

### ISSUE THREAD

**Issue by FedericoNegri** [ansys/pyhps#342]
The version dropdown only shows the dev version, which points to https://rep.docs.pyansys.com/dev that doesn't exist anymore.

**Comment by FedericoNegri** [comment]
@klmcadams @RobPasMue could you maybe take a look? thanks

**Comment by RobPasMue** [comment]
Let me have a look at that

**Comment by RobPasMue** [comment]
Had to do a new release so that the changes were taken into account everywhere
